# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PiratePlay\views\collections.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CollectionsWidget(object):
    def setupUi(self, CollectionsWidget):
        CollectionsWidget.setObjectName("CollectionsWidget")
        CollectionsWidget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(CollectionsWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CollectionsScrollArea = QtWidgets.QScrollArea(CollectionsWidget)
        self.CollectionsScrollArea.setWidgetResizable(True)
        self.CollectionsScrollArea.setObjectName("CollectionsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 798, 598))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.CollectionsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.CollectionsScrollArea)

        self.retranslateUi(CollectionsWidget)
        QtCore.QMetaObject.connectSlotsByName(CollectionsWidget)

    def retranslateUi(self, CollectionsWidget):
        _translate = QtCore.QCoreApplication.translate
        CollectionsWidget.setWindowTitle(_translate("CollectionsWidget", "Collections"))
        self.label.setText(_translate("CollectionsWidget", "Collections"))
