# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PiratePlay\views\discover.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiscoverWidget(object):
    def setupUi(self, DiscoverWidget):
        DiscoverWidget.setObjectName("DiscoverWidget")
        DiscoverWidget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(DiscoverWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DiscoverScrollArea = QtWidgets.QScrollArea(DiscoverWidget)
        self.DiscoverScrollArea.setWidgetResizable(True)
        self.DiscoverScrollArea.setObjectName("DiscoverScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 798, 598))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.DiscoverScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.DiscoverScrollArea)

        self.retranslateUi(DiscoverWidget)
        QtCore.QMetaObject.connectSlotsByName(DiscoverWidget)

    def retranslateUi(self, DiscoverWidget):
        _translate = QtCore.QCoreApplication.translate
        DiscoverWidget.setWindowTitle(_translate("DiscoverWidget", "Discover"))
        self.label.setText(_translate("DiscoverWidget", "Discover"))
