# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PiratePlay\views\downloads.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadsWidget(object):
    def setupUi(self, DownloadsWidget):
        DownloadsWidget.setObjectName("DownloadsWidget")
        DownloadsWidget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(DownloadsWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DownloadsScrollArea = QtWidgets.QScrollArea(DownloadsWidget)
        self.DownloadsScrollArea.setWidgetResizable(True)
        self.DownloadsScrollArea.setObjectName("DownloadsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 798, 598))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.DownloadsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.DownloadsScrollArea)

        self.retranslateUi(DownloadsWidget)
        QtCore.QMetaObject.connectSlotsByName(DownloadsWidget)

    def retranslateUi(self, DownloadsWidget):
        _translate = QtCore.QCoreApplication.translate
        DownloadsWidget.setWindowTitle(_translate("DownloadsWidget", "Downloads"))
        self.label.setText(_translate("DownloadsWidget", "Downloads"))
