# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PiratePlay\views\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWidget(object):
    def setupUi(self, HomeWidget):
        HomeWidget.setObjectName("HomeWidget")
        HomeWidget.resize(1120, 586)
        self.verticalLayout = QtWidgets.QVBoxLayout(HomeWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeScrollArea = QtWidgets.QScrollArea(HomeWidget)
        self.homeScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.homeScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.homeScrollArea.setWidgetResizable(True)
        self.homeScrollArea.setObjectName("homeScrollArea")
        self.homeScrollAreaContent = QtWidgets.QWidget()
        self.homeScrollAreaContent.setGeometry(QtCore.QRect(0, 0, 1101, 1312))
        self.homeScrollAreaContent.setObjectName("homeScrollAreaContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.homeScrollAreaContent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.homeScrollAreaContent)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalScrollArea_CurrentWatching = QtWidgets.QScrollArea(self.homeScrollAreaContent)
        self.horizontalScrollArea_CurrentWatching.setMinimumSize(QtCore.QSize(0, 300))
        self.horizontalScrollArea_CurrentWatching.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.horizontalScrollArea_CurrentWatching.setWidgetResizable(True)
        self.horizontalScrollArea_CurrentWatching.setObjectName("horizontalScrollArea_CurrentWatching")
        self.currentWatchingContent = QtWidgets.QWidget()
        self.currentWatchingContent.setGeometry(QtCore.QRect(0, 0, 1081, 298))
        self.currentWatchingContent.setObjectName("currentWatchingContent")
        self.horizontalScrollArea_CurrentWatching.setWidget(self.currentWatchingContent)
        self.verticalLayout_2.addWidget(self.horizontalScrollArea_CurrentWatching)
        self.label_2 = QtWidgets.QLabel(self.homeScrollAreaContent)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalScrollArea_TrendingsMovies = QtWidgets.QScrollArea(self.homeScrollAreaContent)
        self.horizontalScrollArea_TrendingsMovies.setMinimumSize(QtCore.QSize(0, 300))
        self.horizontalScrollArea_TrendingsMovies.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.horizontalScrollArea_TrendingsMovies.setWidgetResizable(True)
        self.horizontalScrollArea_TrendingsMovies.setObjectName("horizontalScrollArea_TrendingsMovies")
        self.trendingMoviesContent = QtWidgets.QWidget()
        self.trendingMoviesContent.setGeometry(QtCore.QRect(0, 0, 1081, 298))
        self.trendingMoviesContent.setObjectName("trendingMoviesContent")
        self.horizontalScrollArea_TrendingsMovies.setWidget(self.trendingMoviesContent)
        self.verticalLayout_2.addWidget(self.horizontalScrollArea_TrendingsMovies)
        self.label_3 = QtWidgets.QLabel(self.homeScrollAreaContent)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalScrollArea_TrendingsSeries = QtWidgets.QScrollArea(self.homeScrollAreaContent)
        self.horizontalScrollArea_TrendingsSeries.setMinimumSize(QtCore.QSize(0, 300))
        self.horizontalScrollArea_TrendingsSeries.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.horizontalScrollArea_TrendingsSeries.setWidgetResizable(True)
        self.horizontalScrollArea_TrendingsSeries.setObjectName("horizontalScrollArea_TrendingsSeries")
        self.trendingSeriesContent = QtWidgets.QWidget()
        self.trendingSeriesContent.setGeometry(QtCore.QRect(0, 0, 1081, 298))
        self.trendingSeriesContent.setObjectName("trendingSeriesContent")
        self.horizontalScrollArea_TrendingsSeries.setWidget(self.trendingSeriesContent)
        self.verticalLayout_2.addWidget(self.horizontalScrollArea_TrendingsSeries)
        self.label_4 = QtWidgets.QLabel(self.homeScrollAreaContent)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalScrollArea_TrendingsAnimes = QtWidgets.QScrollArea(self.homeScrollAreaContent)
        self.horizontalScrollArea_TrendingsAnimes.setMinimumSize(QtCore.QSize(0, 300))
        self.horizontalScrollArea_TrendingsAnimes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.horizontalScrollArea_TrendingsAnimes.setWidgetResizable(True)
        self.horizontalScrollArea_TrendingsAnimes.setObjectName("horizontalScrollArea_TrendingsAnimes")
        self.trendingAnimeContent = QtWidgets.QWidget()
        self.trendingAnimeContent.setGeometry(QtCore.QRect(0, 0, 1081, 298))
        self.trendingAnimeContent.setObjectName("trendingAnimeContent")
        self.horizontalScrollArea_TrendingsAnimes.setWidget(self.trendingAnimeContent)
        self.verticalLayout_2.addWidget(self.horizontalScrollArea_TrendingsAnimes)
        self.homeScrollArea.setWidget(self.homeScrollAreaContent)
        self.verticalLayout.addWidget(self.homeScrollArea)

        self.retranslateUi(HomeWidget)
        QtCore.QMetaObject.connectSlotsByName(HomeWidget)

    def retranslateUi(self, HomeWidget):
        _translate = QtCore.QCoreApplication.translate
        HomeWidget.setWindowTitle(_translate("HomeWidget", "Home"))
        self.label.setText(_translate("HomeWidget", "Continue Watching"))
        self.label_2.setText(_translate("HomeWidget", "Trending Movies"))
        self.label_3.setText(_translate("HomeWidget", "Trending Series"))
        self.label_4.setText(_translate("HomeWidget", "Trending Anime"))
