# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PiratePlay\views\player.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayerWidget(object):
    def setupUi(self, PlayerWidget):
        PlayerWidget.setObjectName("PlayerWidget")
        PlayerWidget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlayerWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PlayerScrollArea = QtWidgets.QScrollArea(PlayerWidget)
        self.PlayerScrollArea.setWidgetResizable(True)
        self.PlayerScrollArea.setObjectName("PlayerScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 798, 598))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.PlayerScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.PlayerScrollArea)

        self.retranslateUi(PlayerWidget)
        QtCore.QMetaObject.connectSlotsByName(PlayerWidget)

    def retranslateUi(self, PlayerWidget):
        _translate = QtCore.QCoreApplication.translate
        PlayerWidget.setWindowTitle(_translate("PlayerWidget", "Player"))
        self.label.setText(_translate("PlayerWidget", "Player"))
