# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PiratePlay\views\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        SettingsWidget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsTabWidget = QtWidgets.QTabWidget(SettingsWidget)
        self.settingsTabWidget.setObjectName("settingsTabWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.displayLayout = QtWidgets.QVBoxLayout(self.generalTab)
        self.displayLayout.setObjectName("displayLayout")
        self.settingsTabWidget.addTab(self.generalTab, "")
        self.verticalLayout.addWidget(self.settingsTabWidget)

        self.retranslateUi(SettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        SettingsWidget.setWindowTitle(_translate("SettingsWidget", "Settings"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.generalTab), _translate("SettingsWidget", "General"))
